### PR TITLE
update rest mixin

### PR DESCRIPTION
**Pull request by lukekarrys**

### CODE REVIEW

**Comment by lukekarrys** [comment]
@wraithgar @kamilogorek @latentflip Anyone want to +1?

This will be a major version bump like https://github.com/AmpersandJS/ampersand-collection-rest-mixin/pull/10 and https://github.com/AmpersandJS/ampersand-model/pull/42

**Comment by wraithgar** [comment]
Yep +1 as discussed

**Comment by latentflip** [comment]
+1

**Comment by latentflip** [comment]
Released as 3.0.0

**Pull request merged**
