### PR TITLE
switch to lodash-mixin, update deps

### PR DESCRIPTION
**Pull request by wraithgar**
Closes https://github.com/AmpersandJS/ampersand-rest-collection/issues/22

### CODE REVIEW

**Comment by HenrikJoreteg** [comment]
Needs corresponding updates to readme, but otherwise +1

**Comment by wraithgar** [comment]
Aw crap I forgot the readme.

**Comment by HenrikJoreteg** [comment]
also, needs to be major version bump when we release, since some aliases were removed

**Comment by nlf** [comment]
:+1:

**Comment by nlf** [comment]
I'll get the README updates when I get a chance

**Comment by klaemo** [comment]
:+1: and yes, it needs a major version bump :)

**Comment by HenrikJoreteg** [comment]
Looks good to me :shipit:

**Comment by wraithgar** [comment]
shipped as `v4.0.0`

**Pull request merged**
